### ISSUE TITLE
Look into Angular Elements as possible bridge between platforms

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-oss#97]
## Goal

Determine if Angular Elements is a reasonable approach to allow this library to support multiple JS frameworks.

### Tasks

- [ ] Convert `TsIconComponent` to a custom web component
- [ ] Convert `TsButtonComponent` to a custom web component
- [ ] Test consuming one web component into another (verifying our build tool capability)
- [ ] Test component:
  - [ ] Use in an AngularJS app
  - [ ] Use in a VueJS app
  - [ ] Use in a React app
  - [ ] Use in a an Angular test environment
- [ ] Compare web component size to standard size (kb)

### What to document

- How is usage different?
- How would our documentation need to change?
- Are there speed differences?
- Are there bundle size differences?

---

#### Resources

- https://www.telerik.com/blogs/getting-started-with-angular-elements
- https://github.com/nrwl/playbook-angular-v6-elements-example/blob/master/elements/polyfills.ts#L81-L87
- https://blog.bitsrc.io/creating-a-reusable-accordion-component-that-works-anywhere-2f2add05baa4
- https://egghead.io/courses/getting-started-with-angular-elements
